### ISSUE TITLE
Consider using WebExtensions APIS

### ISSUE THREAD

**Issue by groovecoder** [nhnt11/BreachAlerts#3]
To avoid the overhead of enabling legacy extensions and to simplify the code-base, this could be refactored into WebExtensions APIs. Specifically, [`webRequest`](https://developer.mozilla.org/Add-ons/WebExtensions/API/webRequest/) and [`notifications`](https://developer.mozilla.org/Add-ons/WebExtensions/API/notifications) E.g.,

#### background.js
```
const BREACHES_URL = "..."
let siteSet = new Set();

async function initSiteList() {
  const breachesResponse = await fetch(BREACHES_URL);
  const breachesJSON = breachesResponse.json();
  siteSet = new Set(breachesJSON.map(site => site.Domain));
}

function initOnResponseStarted() {
  browser.webRequest.onResponseStarted.addListener(details => {
    if (siteSet.has(details.url.replace("www.",""))) {
      notifications.create({...});
    }
  }...);
}

initSiteList();
initOnResponseStarted();
```

**Comment by nhnt11** [comment]
Keeping in mind future portability of this code into m-c, I'm going to keep this as a legacy extension.
