### ISSUE TITLE
Privacy issues

### ISSUE THREAD

**Issue by ClundXIII** [nhnt11/BreachAlerts#4]
Hi,

I have some question about the way you verify if an user "has been pwned". Are you sending the email to https://haveibeenpwned.com/ ?
If yes, will this be standard behavior when being integrated into Firefox core?

(I took the original mention of the problem from here:
https://gnusocial.de/notice/12301756 )

Simon

**Comment by nhnt11** [comment]
We're still working out the details of how this will work; haveibeenpwned offers a hash set API that allows consumers to avoid having to share user data. In any case, if we are asking for any user data it will certainly be opt-in.
