### ISSUE TITLE
Add sample server/smtp-credentials.json file?

### ISSUE THREAD

**Issue by pdehaan** [nhnt11/BreachAlerts#9]
Looking through the code, it only looks like it has 2 fields, but may be nice to include a dummy "server/smtp-credentials.json.sample" file with something like:

```json
{
  "username": "xxx",
  "password": "yyy"
}
```

**Comment by pdehaan** [comment]
Nevermind, just saw updated README

**Comment by nhnt11** [comment]
This is a good idea! FWIW I was considering doing it along with un-hardcoding the smtp server details in a future commit. :)
